@host = http://localhost:9999

### Adicionar dindin
POST {{host}}/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo": "c",
  "descricao": "danada"
}

### Gastar dindin
POST {{host}}/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 10000,
  "tipo": "d",
  "descricao": "debito"
}

### Extrato
GET {{host}}/clientes/1/extrato

### Limpar
POST {{host}}/clear

